"""
26-week study schedule: Feb 20, 2026 → Aug 20, 2026
Generates a day-by-day plan from weekly templates.

Study windows:
  Weekdays (Mon-Fri):
    Morning block: 8:00 – 10:00 AM  → 2 hours  (deep work: coding, LeetCode, projects)
    Evening block: 9:00 – 10:30 PM  → 1–1.5 hours (lighter: videos, reading, notes)
    Total: ~3.25 hours/day
  Weekends (Sat-Sun): flexible → 7 hours
  Weekly total: ~30+ hours  ·  Program total: ~780+ hours over 26 weeks
"""
from datetime import date, timedelta
from typing import List, Dict

START_DATE = date(2026, 2, 20)  # Friday

# ── Weekly plan templates ────────────────────────────────────────────
# Each week has 7 day-slots. Index 0 = first day of that week (always Friday
# since we start on a Friday and cycle every 7 days).
# Order within each week: Fri, Sat, Sun, Mon, Tue, Wed, Thu
# "hours" will be auto-set: 3.25 for weekdays (2h AM + 1.25h PM), 7 for weekends.

WEEKLY_PLANS: List[Dict] = [
    # ═══════════════════════════════════════════════════════════════════
    # PHASE 1A – Python Proficiency (Weeks 1-4)
    # ═══════════════════════════════════════════════════════════════════
    {   # Week 1: CS50P Lectures 0-3 + Environment Setup (REFRESHER – you did half of CS50P)
        "week": 1,
        "phase": "Phase 1: Python & DSA",
        "theme": "Python Foundations – CS50P Lectures 0-3 (Refresher)",
        "days": [
            {"topic": "Setup & CS50P Lecture 0: Functions, Variables",
             "tasks": ["Install Python 3.11+, VS Code, Git", "Watch CS50P Lecture 0", "Complete Problem Set 0", "Create GitHub repo 'fde-journey'"],
             "resources": ["https://cs50.harvard.edu/python/"]},
            {"topic": "CS50P Lecture 1: Conditionals + Lecture 2: Loops",
             "tasks": ["Watch CS50P Lecture 1", "Complete Problem Set 1", "Watch CS50P Lecture 2", "Complete Problem Set 2", "Practice: write 3 small scripts using loops & conditionals"],
             "resources": ["https://cs50.harvard.edu/python/"]},
            {"topic": "CS50P Lecture 3: Exceptions + Review",
             "tasks": ["Watch CS50P Lecture 3", "Complete Problem Set 3", "LeetCode Easy: Two Sum (#1)", "LeetCode Easy: Valid Parentheses (#20)", "Review all week 1 code, add type hints"],
             "resources": ["https://cs50.harvard.edu/python/", "https://leetcode.com/problems/two-sum/"]},
            {"topic": "Python Practice – Strings & Lists",
             "tasks": ["Solve 3 easy string manipulation exercises", "Practice list comprehensions", "Read: Python Type Hints documentation"],
             "resources": ["https://docs.python.org/3/library/typing.html"]},
            {"topic": "Python Practice – Dictionaries & Sets",
             "tasks": ["Practice dict/set operations", "LeetCode Easy: Contains Duplicate (#217)", "Write a script to count word frequencies in a text file"],
             "resources": ["https://leetcode.com/problems/contains-duplicate/"]},
            {"topic": "Python Practice – File I/O Basics",
             "tasks": ["Read/write CSV files with Python", "Practice error handling (try/except)", "Build: simple log file parser"],
             "resources": ["https://docs.python.org/3/tutorial/inputoutput.html"]},
            {"topic": "Week 1 Review & LeetCode",
             "tasks": ["Review all Problem Sets 0-3", "LeetCode Easy: Best Time to Buy and Sell Stock (#121)", "Push all code to GitHub"],
             "resources": ["https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"]},
        ],
    },
    {   # Week 2: CS50P Lectures 4-6 (Libraries, Unit Tests, File I/O) – fast track
        "week": 2,
        "phase": "Phase 1: Python & DSA",
        "theme": "Python Intermediate – CS50P Lectures 4-6 (Refresher)",
        "days": [
            {"topic": "CS50P Lecture 4: Libraries",
             "tasks": ["Watch CS50P Lecture 4", "Complete Problem Set 4", "Explore: requests, json, csv modules"],
             "resources": ["https://cs50.harvard.edu/python/"]},
            {"topic": "CS50P Lecture 5: Unit Tests",
             "tasks": ["Watch CS50P Lecture 5", "Complete Problem Set 5", "Learn pytest basics", "Write tests for your Week 1 scripts", "Practice: test-driven development on a small function"],
             "resources": ["https://cs50.harvard.edu/python/", "https://docs.pytest.org/"]},
            {"topic": "CS50P Lecture 6: File I/O ⭐",
             "tasks": ["Watch CS50P Lecture 6 (KEY lecture)", "Complete Problem Set 6", "Build: CSV data cleaner script", "Practice reading/writing JSON files", "LeetCode Easy: Valid Anagram (#242)"],
             "resources": ["https://cs50.harvard.edu/python/", "https://leetcode.com/problems/valid-anagram/"]},
            {"topic": "File I/O Deep Dive",
             "tasks": ["Practice: parse a large CSV with error handling", "Learn pathlib module", "LeetCode Medium: Group Anagrams (#49)"],
             "resources": ["https://leetcode.com/problems/group-anagrams/"]},
            {"topic": "JSON & API Data Processing",
             "tasks": ["Fetch data from a public API (JSONPlaceholder)", "Parse and transform nested JSON", "Write results to CSV with proper encoding"],
             "resources": ["https://jsonplaceholder.typicode.com/"]},
            {"topic": "Unit Testing Practice",
             "tasks": ["Write comprehensive tests for File I/O scripts", "Learn pytest fixtures and parametrize", "Practice mocking with unittest.mock"],
             "resources": ["https://docs.pytest.org/en/stable/fixture.html"]},
            {"topic": "Week 2 Review & LeetCode",
             "tasks": ["Review Problem Sets 4-6", "LeetCode Medium: Top K Frequent Elements (#347)", "Push all code to GitHub with tests"],
             "resources": ["https://leetcode.com/problems/top-k-frequent-elements/"]},
        ],
    },
    {   # Week 3: CS50P Lectures 7-8 (Regex, OOP) + PII Project Start
        "week": 3,
        "phase": "Phase 1: Python & DSA",
        "theme": "Python Advanced – Regex & OOP",
        "days": [
            {"topic": "CS50P Lecture 7: Regular Expressions ⭐",
             "tasks": ["Watch CS50P Lecture 7", "Complete Problem Set 7", "Practice: email/phone regex patterns"],
             "resources": ["https://cs50.harvard.edu/python/", "https://regex101.com/"]},
            {"topic": "CS50P Lecture 8: OOP ⭐ (Part 1)",
             "tasks": ["Watch CS50P Lecture 8", "Complete Problem Set 8 (first half)", "Build: DataRecord class with validation", "Practice: inheritance and dunder methods", "LeetCode Medium: Longest Substring Without Repeating (#3)"],
             "resources": ["https://cs50.harvard.edu/python/", "https://leetcode.com/problems/longest-substring-without-repeating-characters/"]},
            {"topic": "CS50P Lecture 8: OOP ⭐ (Part 2) + Regex Review",
             "tasks": ["Complete Problem Set 8", "Build: PII detector using regex (SSN, email, phone)", "Practice: class composition", "LeetCode Medium: Encode and Decode Strings (#271)", "Start planning PII Redaction project"],
             "resources": ["https://cs50.harvard.edu/python/"]},
            {"topic": "PII Redaction Project – Design",
             "tasks": ["Design data cleaning pipeline architecture", "Create project structure with OOP", "Write regex patterns for PII detection (SSN, DOB, names)"],
             "resources": ["https://microsoft.github.io/presidio/"]},
            {"topic": "PII Redaction Project – Implementation",
             "tasks": ["Implement PII scanner class", "Add CSV/JSON input support", "LeetCode Medium: Product of Array Except Self (#238)"],
             "resources": ["https://leetcode.com/problems/product-of-array-except-self/"]},
            {"topic": "PII Redaction Project – Testing",
             "tasks": ["Write unit tests for PII detection", "Test edge cases (partial matches, false positives)", "Add logging to the pipeline"],
             "resources": []},
            {"topic": "Week 3 Review & LeetCode",
             "tasks": ["Review OOP and Regex concepts", "LeetCode Medium: Maximum Subarray (#53)", "Polish PII project, push to GitHub"],
             "resources": ["https://leetcode.com/problems/maximum-subarray/"]},
        ],
    },
    {   # Week 4: CS50P Lecture 9 + PII Project Complete + Advanced Python
        "week": 4,
        "phase": "Phase 1: Python & DSA",
        "theme": "Advanced Python & Project Completion",
        "days": [
            {"topic": "CS50P Lecture 9: Et Cetera",
             "tasks": ["Watch CS50P Lecture 9", "Practice: sets, global, constants, type hints", "Learn: dataclasses and enums"],
             "resources": ["https://cs50.harvard.edu/python/"]},
            {"topic": "PII Redaction Project – SQL Output",
             "tasks": ["Add SQLite output to PII pipeline", "Implement redacted data → SQL table writer", "Build: command-line interface for the tool", "Write integration tests", "LeetCode Medium: 3Sum (#15)"],
             "resources": ["https://leetcode.com/problems/3sum/"]},
            {"topic": "PII Project Polish + Python Decorators",
             "tasks": ["Add README and documentation to PII project", "Learn Python decorators", "Learn context managers (with statement)", "Practice: generator functions", "LeetCode Medium: Container With Most Water (#11)"],
             "resources": ["https://leetcode.com/problems/container-with-most-water/"]},
            {"topic": "Python Advanced – Virtual Environments & Packaging",
             "tasks": ["Learn venv, pip, requirements.txt", "Understand __init__.py and package structure", "LeetCode Medium: Merge Intervals (#56)"],
             "resources": ["https://leetcode.com/problems/merge-intervals/"]},
            {"topic": "Pandas Fundamentals (Part 1)",
             "tasks": ["Install pandas, learn DataFrame basics", "Load CSV data, basic filtering and grouping", "Practice: pandas vs raw Python file I/O"],
             "resources": ["https://pandas.pydata.org/docs/getting_started/"]},
            {"topic": "Pandas Fundamentals (Part 2)",
             "tasks": ["Pandas: merge, join, pivot tables", "Data cleaning with pandas (nulls, dtypes)", "Apply pandas to PII project for data profiling"],
             "resources": ["https://pandas.pydata.org/docs/user_guide/merging.html"]},
            {"topic": "Phase 1A Checkpoint",
             "tasks": ["Review all CS50P concepts", "Verify PII project is complete and on GitHub", "Self-assessment: can you parse 1GB JSON into SQL?", "LeetCode Medium: Search in Rotated Sorted Array (#33)"],
             "resources": ["https://leetcode.com/problems/search-in-rotated-sorted-array/"]},
        ],
    },
    # ═══════════════════════════════════════════════════════════════════
    # PHASE 1B – DSA Deep Dive (Weeks 5-8)
    # ═══════════════════════════════════════════════════════════════════
    {   # Week 5: HashMaps & Strings + Advanced Python
        "week": 5,
        "phase": "Phase 1: Python & DSA",
        "theme": "DSA – HashMaps & Strings",
        "days": [
            {"topic": "HashMap Patterns",
             "tasks": ["Study: hash table internals in Python (dict)", "LeetCode Medium: Two Sum II (#167)", "LeetCode Medium: Longest Consecutive Sequence (#128)"],
             "resources": ["https://leetcode.com/problems/longest-consecutive-sequence/"]},
            {"topic": "String Manipulation Deep Dive",
             "tasks": ["Study: string algorithms (sliding window, two pointers)", "LeetCode Medium: Minimum Window Substring (#76)", "LeetCode Medium: Valid Palindrome II (#680)", "Practice: regex-based string parsing", "Build: log file analyzer with pattern matching"],
             "resources": ["https://leetcode.com/problems/minimum-window-substring/"]},
            {"topic": "Advanced Python – Generators & Itertools",
             "tasks": ["Learn generator expressions and yield", "Practice itertools (combinations, permutations, chain)", "Build: memory-efficient large file processor", "LeetCode Medium: Implement Trie (#208)", "Code review: optimize previous solutions"],
             "resources": ["https://docs.python.org/3/library/itertools.html"]},
            {"topic": "DSA – Two Pointer Technique",
             "tasks": ["Study two-pointer patterns", "LeetCode Medium: Trapping Rain Water (#42)", "Practice: sorted array problems"],
             "resources": ["https://leetcode.com/problems/trapping-rain-water/"]},
            {"topic": "Python – Error Handling Mastery",
             "tasks": ["Custom exception classes", "Logging best practices (logging module)", "LeetCode Medium: Valid Sudoku (#36)"],
             "resources": ["https://docs.python.org/3/library/logging.html"]},
            {"topic": "Build: Data Pipeline Script",
             "tasks": ["Design a multi-step data pipeline", "Read from API → clean → transform → load to SQLite", "Add error handling and retry logic"],
             "resources": []},
            {"topic": "Week 5 Review + Networking",
             "tasks": ["Review HashMap and String patterns", "Push data pipeline project to GitHub", "LeetCode review: redo any unsolved problems", "🤝 Networking: reach out to 2 FDEs/Solutions Engineers on LinkedIn"],
             "resources": []},
        ],
    },
    {   # Week 6: Arrays & Sliding Window
        "week": 6,
        "phase": "Phase 1: Python & DSA",
        "theme": "DSA – Arrays & Sliding Window",
        "days": [
            {"topic": "Sliding Window Pattern",
             "tasks": ["Study sliding window technique", "LeetCode Medium: Maximum Average Subarray (#643)", "LeetCode Medium: Longest Repeating Character Replacement (#424)"],
             "resources": ["https://leetcode.com/problems/longest-repeating-character-replacement/"]},
            {"topic": "Array Manipulation + Sorting",
             "tasks": ["Study: sorting algorithms (merge sort, quick sort)", "LeetCode Medium: Sort Colors (#75)", "LeetCode Medium: Kth Largest Element (#215)", "Practice: custom sorting with key functions", "Build: data deduplication tool"],
             "resources": ["https://leetcode.com/problems/kth-largest-element-in-an-array/"]},
            {"topic": "Binary Search Applications",
             "tasks": ["Study binary search patterns", "LeetCode Medium: Find Minimum in Rotated Sorted Array (#153)", "LeetCode Medium: Search a 2D Matrix (#74)", "Practice: bisect module in Python", "Apply binary search to data lookup problems"],
             "resources": ["https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/"]},
            {"topic": "Python – Collections Module",
             "tasks": ["Learn: Counter, defaultdict, OrderedDict, deque", "Refactor previous solutions using collections", "LeetCode Medium: Subarray Sum Equals K (#560)"],
             "resources": ["https://leetcode.com/problems/subarray-sum-equals-k/"]},
            {"topic": "Build: ETL Pipeline with Pandas",
             "tasks": ["Design ETL for a public dataset (Kaggle)", "Extract → Transform (pandas) → Load (SQLite)", "Add data validation checks"],
             "resources": ["https://www.kaggle.com/datasets"]},
            {"topic": "ETL Pipeline – Testing & Polish",
             "tasks": ["Write tests for ETL pipeline", "Add CLI arguments with argparse", "Document with docstrings and README"],
             "resources": []},
            {"topic": "Week 6 Review",
             "tasks": ["Review sliding window and binary search", "Update GitHub portfolio", "LeetCode: attempt any 2 unsolved mediums"],
             "resources": []},
        ],
    },
    {   # Week 7: Stacks, Queues & Trees
        "week": 7,
        "phase": "Phase 1: Python & DSA",
        "theme": "DSA – Stacks, Queues & Trees",
        "days": [
            {"topic": "Stack & Queue Patterns",
             "tasks": ["Study stack/queue implementations", "LeetCode Medium: Daily Temperatures (#739)", "LeetCode Medium: Evaluate Reverse Polish Notation (#150)"],
             "resources": ["https://leetcode.com/problems/daily-temperatures/"]},
            {"topic": "Tree Fundamentals",
             "tasks": ["Study binary tree traversals (BFS/DFS)", "LeetCode Medium: Binary Tree Level Order Traversal (#102)", "LeetCode Medium: Validate Binary Search Tree (#98)", "Implement tree from scratch in Python", "Practice: recursive vs iterative traversal"],
             "resources": ["https://leetcode.com/problems/binary-tree-level-order-traversal/"]},
            {"topic": "Graph Basics (Important for Agents)",
             "tasks": ["Study graph representations (adjacency list)", "BFS and DFS on graphs", "LeetCode Medium: Number of Islands (#200)", "LeetCode Medium: Clone Graph (#133)", "Connection: graph traversal → agent state machines"],
             "resources": ["https://leetcode.com/problems/number-of-islands/"]},
            {"topic": "Python – Async Basics",
             "tasks": ["Learn asyncio fundamentals", "Practice: async HTTP requests with aiohttp", "Compare sync vs async for data fetching"],
             "resources": ["https://docs.python.org/3/library/asyncio.html"]},
            {"topic": "Build: Async Data Fetcher",
             "tasks": ["Build async multi-API data aggregator", "Handle rate limiting and retries", "Add proper error handling for network failures"],
             "resources": []},
            {"topic": "Python – Type Hints & Mypy",
             "tasks": ["Advanced type hints (Optional, Union, TypeVar)", "Run mypy on all your projects", "Fix type errors across your codebase"],
             "resources": ["https://mypy.readthedocs.io/"]},
            {"topic": "Week 7 Review",
             "tasks": ["Review trees and graphs", "Ensure all projects have type hints", "LeetCode: attempt 2 tree/graph problems"],
             "resources": []},
        ],
    },
    {   # Week 8: Consolidation & Phase 1 Wrap-up
        "week": 8,
        "phase": "Phase 1: Python & DSA",
        "theme": "Phase 1 Consolidation & Review",
        "days": [
            {"topic": "LeetCode Sprint (Arrays & Strings)",
             "tasks": ["Solve 3 medium problems (arrays/strings)", "Focus on clean code with type hints", "Time yourself: aim for 25 min per medium"],
             "resources": ["https://leetcode.com/problemset/all/"]},
            {"topic": "LeetCode Sprint (HashMaps & Mixed)",
             "tasks": ["Solve 3 medium problems (hashmaps)", "Solve 1 problem from each: stack, tree, graph", "Write up solutions with Big-O analysis", "Review all 30 problems solved so far", "Identify weak areas for future practice"],
             "resources": []},
            {"topic": "Portfolio Review Day",
             "tasks": ["Review all GitHub projects", "Ensure each project has: README, tests, type hints", "Update GitHub profile and pinned repos", "Write 1 blog post / LinkedIn post about your journey", "Record: what you learned in Phase 1"],
             "resources": []},
            {"topic": "Phase 1 → Phase 2 Transition",
             "tasks": ["Install LangChain and dependencies", "Read LangChain quickstart docs", "LeetCode: 1 medium problem for maintenance"],
             "resources": ["https://python.langchain.com/docs/get_started/quickstart"]},
            {"topic": "LangChain Environment Setup",
             "tasks": ["Set up OpenAI API key", "Run first LangChain 'Hello World'", "Understand: Models, Prompts, Chains"],
             "resources": ["https://python.langchain.com/docs/"]},
            {"topic": "Prompt Engineering Fundamentals",
             "tasks": ["Study: zero-shot, few-shot, chain-of-thought", "Practice: structured output (JSON mode)", "Build: 5 different prompt templates"],
             "resources": ["https://www.promptingguide.ai/"]},
            {"topic": "Phase 1 Complete – Celebrate! 🎉",
             "tasks": ["Final review of all Phase 1 material", "Update resume with new Python skills", "Plan Phase 2 goals and milestones"],
             "resources": []},
        ],
    },
    # ═══════════════════════════════════════════════════════════════════
    # PHASE 2A – Agentic AI & Frameworks (Weeks 9-14)
    # ═══════════════════════════════════════════════════════════════════
    {   # Week 9: LangChain Fundamentals
        "week": 9,
        "phase": "Phase 2: Agentic AI & Modern Data Stack",
        "theme": "LangChain – Prompts, Chains, Models",
        "days": [
            {"topic": "LangChain Core: Models & Prompts",
             "tasks": ["Udemy LangChain course: Sections 1-2", "Practice: ChatOpenAI, PromptTemplate", "Build: multi-prompt chatbot"],
             "resources": ["https://www.udemy.com/course/langchain-develop-llm-powered-applications-with-langchain/"]},
            {"topic": "LangChain Chains & Output Parsers",
             "tasks": ["Udemy course: Section 3", "Build: structured output chain (JSON)", "Practice: SequentialChain, RouterChain", "Learn: Pydantic output parsers", "LeetCode maintenance: 1 medium problem"],
             "resources": []},
            {"topic": "LangChain Memory Systems",
             "tasks": ["Udemy course: Section 4", "Implement: ConversationBufferMemory", "Implement: ConversationSummaryMemory", "Build: chatbot with persistent memory", "Compare memory strategies for different use cases"],
             "resources": []},
            {"topic": "LCEL (LangChain Expression Language)",
             "tasks": ["Learn LCEL pipe syntax", "Convert chains to LCEL", "Practice: streaming and batch operations"],
             "resources": ["https://python.langchain.com/docs/expression_language/"]},
            {"topic": "LangChain Tools & Agents Intro",
             "tasks": ["Study: ReAct agent pattern", "Build: agent with calculator tool", "Learn: custom tool creation"],
             "resources": ["https://python.langchain.com/docs/modules/agents/"]},
            {"topic": "Practice: Build a Research Agent",
             "tasks": ["Build agent that searches web + summarizes", "Add tool for Wikipedia lookup", "Implement error handling for agent failures"],
             "resources": []},
            {"topic": "Week 9 Review + Networking",
             "tasks": ["Review all LangChain concepts", "Push projects to GitHub", "LeetCode: 1 medium problem", "🤝 Networking: reach out to 2 FDEs on LinkedIn", "🤝 Join LangChain Discord community"],
             "resources": []},
        ],
    },
    {   # Week 10: LangChain – Retrievers & Document Loaders
        "week": 10,
        "phase": "Phase 2: Agentic AI & Modern Data Stack",
        "theme": "LangChain – Retrievers & RAG Foundations",
        "days": [
            {"topic": "Document Loaders",
             "tasks": ["Learn: PDF, CSV, JSON, SQL loaders", "Practice: load and split large documents", "Study: text splitting strategies (recursive, semantic)"],
             "resources": ["https://python.langchain.com/docs/modules/data_connection/document_loaders/"]},
            {"topic": "Embeddings & Vector Stores",
             "tasks": ["Understand embedding models (OpenAI, HuggingFace)", "Set up ChromaDB locally", "Build: document embedding pipeline", "Practice: similarity search queries", "Learn: FAISS vs ChromaDB vs Pinecone tradeoffs"],
             "resources": ["https://python.langchain.com/docs/modules/data_connection/vectorstores/"]},
            {"topic": "RAG Pipeline – Build from Scratch",
             "tasks": ["Build complete RAG: load → split → embed → retrieve → generate", "Test with a healthcare PDF document", "Implement: source citation in responses", "Practice: retrieval quality tuning", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "RAG Advanced – Retrieval Strategies",
             "tasks": ["Learn: MMR, similarity threshold, multi-query", "Implement: hybrid search (keyword + semantic)", "Compare retrieval strategies on same dataset"],
             "resources": []},
            {"topic": "RAG Pipeline – Testing & Evaluation",
             "tasks": ["Write tests for RAG pipeline", "Manual evaluation: check answer quality", "Build: evaluation dataset (10 Q&A pairs)"],
             "resources": []},
            {"topic": "Vector Database Deep Dive",
             "tasks": ["Explore Pinecone (free tier)", "Compare: ChromaDB vs Pinecone performance", "Learn: index management and metadata filtering"],
             "resources": ["https://www.pinecone.io/"]},
            {"topic": "Week 10 Review",
             "tasks": ["Review RAG concepts", "Ensure RAG project is on GitHub", "Write up: RAG architecture diagram"],
             "resources": []},
        ],
    },
    {   # Week 11: Build a Full RAG System
        "week": 11,
        "phase": "Phase 2: Agentic AI & Modern Data Stack",
        "theme": "RAG System – Production Build",
        "days": [
            {"topic": "Production RAG Architecture",
             "tasks": ["Design production RAG system architecture", "Implement: document ingestion pipeline", "Add: chunking strategy optimization"],
             "resources": []},
            {"topic": "RAG with Conversation History",
             "tasks": ["Add conversation memory to RAG", "Implement: contextual compression", "Build: follow-up question handling", "Test: multi-turn conversation quality", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "RAG UI with Streamlit",
             "tasks": ["Build Streamlit chat interface for RAG", "Add: document upload feature", "Implement: streaming responses", "Add: source document display", "Polish UI/UX"],
             "resources": ["https://docs.streamlit.io/"]},
            {"topic": "RAG Error Handling & Edge Cases",
             "tasks": ["Handle: no relevant documents found", "Handle: token limit exceeded", "Add: fallback responses and guardrails"],
             "resources": []},
            {"topic": "RAG Performance Optimization",
             "tasks": ["Implement: caching for embeddings", "Optimize: chunk size and overlap", "Benchmark: response latency"],
             "resources": []},
            {"topic": "RAG Project Documentation",
             "tasks": ["Write comprehensive README", "Create architecture diagram (RADIO framework)", "Record demo video or screenshots"],
             "resources": []},
            {"topic": "Week 11 Review + System Design",
             "tasks": ["Final testing of RAG system", "Push to GitHub with documentation", "LeetCode: 1 medium problem", "📐 System Design: draw your RAG architecture using RADIO framework"],
             "resources": []},
        ],
    },
    {   # Week 12: SQL Agents (Bridge your SQL expertise)
        "week": 12,
        "phase": "Phase 2: Agentic AI & Modern Data Stack",
        "theme": "SQL Agents – LLM + SQL Integration ⭐",
        "days": [
            {"topic": "LangChain SQL Agent Basics",
             "tasks": ["Study SQL Agent tutorial", "Set up sample database (Chinook/Northwind)", "Build: basic SQL agent that answers NL questions"],
             "resources": ["https://python.langchain.com/docs/tutorials/sql_qa/"]},
            {"topic": "SQL Agent – Advanced Queries",
             "tasks": ["Handle: complex JOINs via natural language", "Handle: aggregation queries", "Test: agent SQL generation accuracy", "Build: query validation layer", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "SQL Agent – Error Correction ⭐",
             "tasks": ["Implement: SQL error detection", "Build: auto-correction loop (retry with error context)", "Test with intentionally tricky queries", "Log: all generated SQL for audit"],
             "resources": []},
            {"topic": "SQL Agent – Schema Understanding",
             "tasks": ["Teach agent about table relationships", "Implement: dynamic schema injection", "Handle: large schemas (selective table context)"],
             "resources": []},
            {"topic": "SQL Agent – Security Layer",
             "tasks": ["Implement: SQL injection prevention", "Add: read-only query enforcement", "Build: query allowlist/denylist"],
             "resources": []},
            {"topic": "SQL Agent – Integration Testing",
             "tasks": ["Write comprehensive tests for SQL agent", "Test edge cases (empty results, ambiguous queries)", "Performance benchmark: query generation time"],
             "resources": []},
            {"topic": "Week 12 Review",
             "tasks": ["Review SQL agent architecture", "Push to GitHub", "Reflect: connection to your DW experience"],
             "resources": []},
        ],
    },
    {   # Week 13: LangGraph – Multi-Agent Systems
        "week": 13,
        "phase": "Phase 2: Agentic AI & Modern Data Stack",
        "theme": "LangGraph – State Machines & Multi-Agent",
        "days": [
            {"topic": "LangGraph Fundamentals",
             "tasks": ["Study LangGraph: nodes, edges, state", "Build: simple state graph", "Understand: conditional edges and routing"],
             "resources": ["https://langchain-ai.github.io/langgraph/"]},
            {"topic": "LangGraph – Complex Workflows",
             "tasks": ["Build: multi-step reasoning graph", "Implement: human-in-the-loop pattern", "Practice: state management and checkpoints", "Build: approval workflow graph", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "LangGraph – Multi-Agent Collaboration",
             "tasks": ["Build: supervisor agent pattern", "Implement: agent-to-agent delegation", "Practice: shared state between agents", "Test: complex multi-agent scenario"],
             "resources": []},
            {"topic": "LangGraph – Error Correction Loops ⭐",
             "tasks": ["Build: self-correcting SQL agent with LangGraph", "Implement: reflection and retry patterns", "Key skill for capstone project"],
             "resources": []},
            {"topic": "LangGraph – Streaming & Persistence",
             "tasks": ["Implement: streaming agent responses", "Add: checkpoint persistence (SQLite)", "Build: resumable workflows"],
             "resources": []},
            {"topic": "LangGraph + SQL Agent Integration",
             "tasks": ["Integrate LangGraph with your SQL agent", "Build: SQL gen → validation → correction graph", "Test end-to-end workflow"],
             "resources": []},
            {"topic": "Week 13 Review + Networking + System Design",
             "tasks": ["Review LangGraph patterns", "Push integrated project to GitHub", "LeetCode: 1 medium problem", "🤝 Networking: reach out to 2 FDEs on LinkedIn + attend 1 AI meetup", "📐 System Design: draw multi-agent SQL correction system (RADIO)"],
             "resources": []},
        ],
    },
    {   # Week 14: Advanced Agent Patterns + FastAPI
        "week": 14,
        "phase": "Phase 2: Agentic AI & Modern Data Stack",
        "theme": "Advanced Agents & FastAPI",
        "days": [
            {"topic": "FastAPI Fundamentals",
             "tasks": ["Install FastAPI + uvicorn", "Build: REST API with CRUD endpoints", "Learn: Pydantic models for request/response"],
             "resources": ["https://fastapi.tiangolo.com/tutorial/"]},
            {"topic": "FastAPI + LangChain Integration",
             "tasks": ["Expose SQL agent as API endpoint", "Add: streaming endpoint for agent responses", "Implement: async request handling", "Add: API key authentication", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "Agent Deployment Patterns",
             "tasks": ["Study: agent deployment architectures", "Docker basics: Dockerfile, docker-compose", "Containerize your FastAPI + agent app", "Practice: environment variable management", "Learn: health check endpoints"],
             "resources": ["https://docs.docker.com/get-started/"]},
            {"topic": "Agent Observability",
             "tasks": ["Add: LangSmith tracing to your agents", "Implement: custom logging for agent steps", "Build: cost tracking for API calls"],
             "resources": ["https://smith.langchain.com/"]},
            {"topic": "Prompt Engineering Deep Dive",
             "tasks": ["Study: advanced prompting techniques", "Implement: few-shot examples for SQL agent", "Practice: chain-of-thought for complex queries"],
             "resources": ["https://www.promptingguide.ai/"]},
            {"topic": "Phase 2A Project Polish",
             "tasks": ["Code review all Phase 2 projects", "Ensure consistent code style", "Update all READMEs and documentation"],
             "resources": []},
            {"topic": "Week 14 Review",
             "tasks": ["Review FastAPI and deployment concepts", "All Phase 2A code on GitHub", "LeetCode: 1 medium problem"],
             "resources": []},
        ],
    },
    # ═══════════════════════════════════════════════════════════════════
    # PHASE 2B – Modern Data Stack (Weeks 15-16)
    # ═══════════════════════════════════════════════════════════════════
    {   # Week 15: Snowflake
        "week": 15,
        "phase": "Phase 2: Agentic AI & Modern Data Stack",
        "theme": "Snowflake – Cloud Data Warehouse",
        "days": [
            {"topic": "Snowflake Fundamentals",
             "tasks": ["Sign up for Snowflake free trial", "Complete: Hands-on Essentials – Data Warehousing", "Explore: Snowflake Web UI"],
             "resources": ["https://quickstarts.snowflake.com/"]},
            {"topic": "Snowflake – Data Loading & SQL",
             "tasks": ["Practice: COPY INTO, stages, file formats", "Run complex SQL queries in Snowflake", "Compare: Snowflake SQL vs your traditional DW SQL", "Load sample dataset (TPC-H)", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "Snowflake – Advanced Features",
             "tasks": ["Learn: Time Travel, Cloning, Data Sharing", "Practice: Snowpark (Python in Snowflake)", "Understand: virtual warehouses and cost management", "Build: data pipeline from API → Snowflake", "Explore: Snowflake Marketplace"],
             "resources": []},
            {"topic": "Snowflake + Python Integration",
             "tasks": ["Use snowflake-connector-python", "Build: Python script to query Snowflake", "Implement: parameterized queries (secure)"],
             "resources": ["https://docs.snowflake.com/en/developer-guide/python-connector/"]},
            {"topic": "Snowflake Architecture Deep Dive",
             "tasks": ["Study: multi-cluster shared data architecture", "Understand: storage vs compute separation", "Practice: role-based access control (RBAC)"],
             "resources": []},
            {"topic": "Snowflake + LangChain SQL Agent",
             "tasks": ["Connect your SQL agent to Snowflake", "Test NL queries against Snowflake data", "Compare: SQLite vs Snowflake agent performance"],
             "resources": []},
            {"topic": "Week 15 Review",
             "tasks": ["Review Snowflake concepts", "Document: key Snowflake features for interviews", "LeetCode: 1 medium problem"],
             "resources": []},
        ],
    },
    {   # Week 16: dbt (data build tool)
        "week": 16,
        "phase": "Phase 2: Agentic AI & Modern Data Stack",
        "theme": "dbt – Data Transformation",
        "days": [
            {"topic": "dbt Fundamentals",
             "tasks": ["Install dbt-core + dbt-snowflake adapter", "Complete: dbt Fundamentals course", "Build: first dbt project with models"],
             "resources": ["https://courses.getdbt.com/courses/fundamentals"]},
            {"topic": "dbt Models & Materializations",
             "tasks": ["Build: staging and mart models", "Practice: views vs tables vs incremental", "Implement: model documentation and descriptions", "Write dbt tests (unique, not_null, relationships)", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "dbt Advanced – Macros & Packages",
             "tasks": ["Learn: Jinja templating in dbt", "Write custom macros", "Install dbt-utils package", "Build: reusable transformation patterns", "Practice: dbt snapshots for SCD Type 2"],
             "resources": ["https://docs.getdbt.com/docs/build/jinja-macros"]},
            {"topic": "dbt + Snowflake Integration",
             "tasks": ["Run dbt models against Snowflake", "Implement: dbt source freshness tests", "Build: complete ELT pipeline"],
             "resources": []},
            {"topic": "dbt Documentation & Lineage",
             "tasks": ["Generate dbt docs", "Explore lineage graph", "Write comprehensive model descriptions"],
             "resources": []},
            {"topic": "Phase 2 Project Integration",
             "tasks": ["Connect: dbt → Snowflake → SQL Agent pipeline", "Test end-to-end data flow", "Document architecture with RADIO framework"],
             "resources": []},
            {"topic": "Phase 2 Complete – Checkpoint 🎉",
             "tasks": ["Review all Phase 2 material", "Ensure all projects on GitHub", "Update resume with AI/Agent skills", "LinkedIn post about Phase 2 learnings"],
             "resources": []},
        ],
    },
    # ═══════════════════════════════════════════════════════════════════
    # PHASE 3A – AI Security & Compliance (Weeks 17-19)
    # ═══════════════════════════════════════════════════════════════════
    {   # Week 17: OWASP Top 10 for LLMs
        "week": 17,
        "phase": "Phase 3: Security, Evals & Production",
        "theme": "OWASP LLM Top 10 – Security Foundations",
        "days": [
            {"topic": "OWASP LLM Top 10 Overview",
             "tasks": ["Read: OWASP Top 10 for LLMs (full document)", "Study: LLM01 Prompt Injection", "Study: LLM02 Insecure Output Handling"],
             "resources": ["https://owasp.org/www-project-top-10-for-large-language-model-applications/"]},
            {"topic": "OWASP Deep Dive – Injection & Data",
             "tasks": ["Study: LLM03 Training Data Poisoning", "Study: LLM06 Sensitive Info Disclosure", "Implement: input sanitization for your SQL agent", "Build: prompt injection test suite", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "OWASP Deep Dive – Access & Denial",
             "tasks": ["Study: LLM04 Model Denial of Service", "Study: LLM05 Supply Chain Vulnerabilities", "Study: LLM07-10 remaining items", "Document: security checklist for AI applications", "Map OWASP risks to your existing projects"],
             "resources": []},
            {"topic": "Security Implementation – Input Validation",
             "tasks": ["Build: input validation middleware", "Implement: rate limiting for API endpoints", "Add: output filtering for sensitive data"],
             "resources": []},
            {"topic": "Security Implementation – Guardrails",
             "tasks": ["Implement: topic restriction guardrails", "Build: output safety checker", "Test: adversarial prompts against your agent"],
             "resources": []},
            {"topic": "Security Audit of Your Projects",
             "tasks": ["Security review: RAG system", "Security review: SQL agent", "Document findings and fixes"],
             "resources": []},
            {"topic": "Week 17 Review + Networking",
             "tasks": ["Review OWASP Top 10 concepts", "Ensure security layers added to projects", "LeetCode: 1 medium problem", "🤝 Networking: reach out to 2 FDEs on LinkedIn + engage in LangChain GitHub discussions"],
             "resources": []},
        ],
    },
    {   # Week 18: Microsoft Presidio – PII Redaction
        "week": 18,
        "phase": "Phase 3: Security, Evals & Production",
        "theme": "Microsoft Presidio – PII Redaction",
        "days": [
            {"topic": "Presidio Setup & Fundamentals",
             "tasks": ["Install presidio-analyzer and presidio-anonymizer", "Run: basic PII detection on sample text", "Understand: recognizers and operators"],
             "resources": ["https://microsoft.github.io/presidio/"]},
            {"topic": "Presidio – Custom Recognizers",
             "tasks": ["Build: custom recognizer for healthcare data", "Build: custom recognizer for financial data", "Practice: regex-based recognizers", "Test: detection accuracy on your datasets", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "Presidio Integration – SQL Agent",
             "tasks": ["Add PII redaction to SQL agent input", "Add PII redaction to SQL agent output", "Implement: configurable redaction levels", "Test: end-to-end PII protection", "Build: audit log for redacted data"],
             "resources": []},
            {"topic": "Presidio Integration – RAG System",
             "tasks": ["Add PII scanning to document ingestion", "Redact PII before embedding documents", "Test: PII doesn't leak in RAG responses"],
             "resources": []},
            {"topic": "Data Privacy Patterns",
             "tasks": ["Study: HIPAA compliance requirements", "Study: GDPR data handling rules", "Document: data privacy architecture for your projects"],
             "resources": []},
            {"topic": "PII Layer Testing",
             "tasks": ["Write comprehensive PII detection tests", "Test with healthcare, financial, PII datasets", "Benchmark: detection accuracy metrics"],
             "resources": []},
            {"topic": "Week 18 Review",
             "tasks": ["Review Presidio concepts", "All projects now have PII protection", "Push updates to GitHub"],
             "resources": []},
        ],
    },
    {   # Week 19: Security Integration & Advanced Patterns
        "week": 19,
        "phase": "Phase 3: Security, Evals & Production",
        "theme": "Security Integration & Compliance Docs",
        "days": [
            {"topic": "Security Architecture Documentation",
             "tasks": ["Document: threat model for SQL agent", "Create: security architecture diagram", "Write: compliance mapping (OWASP → your controls)"],
             "resources": []},
            {"topic": "Advanced Security – LLM Firewalls",
             "tasks": ["Study: LLM firewall concepts", "Implement: content filtering layer", "Build: moderation chain for agent output", "Test: prompt injection resilience", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "End-to-End Security Testing",
             "tasks": ["Run adversarial tests on all projects", "Test: PII leakage scenarios", "Test: SQL injection via natural language", "Document: security test results", "Fix any vulnerabilities found"],
             "resources": []},
            {"topic": "Security – Secrets Management",
             "tasks": ["Implement: proper API key management", "Use: python-dotenv, environment variables", "Audit: no secrets in code or Git history"],
             "resources": []},
            {"topic": "Mock Interview: Security Questions",
             "tasks": ["Practice: 'How do you handle AI data privacy?'", "Practice: 'Explain OWASP LLM Top 10'", "Practice: 'How would you prevent prompt injection?'"],
             "resources": []},
            {"topic": "Portfolio Security Review",
             "tasks": ["Ensure all projects demonstrate security awareness", "Update READMEs with security sections", "Create: security-focused project summary"],
             "resources": []},
            {"topic": "Week 19 / Phase 3A Review",
             "tasks": ["Review all security concepts", "Phase 3A checkpoint: security skills complete", "LeetCode: 1 medium problem"],
             "resources": []},
        ],
    },
    # ═══════════════════════════════════════════════════════════════════
    # PHASE 3B – Evaluation & Observability (Weeks 20-22)
    # ═══════════════════════════════════════════════════════════════════
    {   # Week 20: Ragas Fundamentals
        "week": 20,
        "phase": "Phase 3: Security, Evals & Production",
        "theme": "Ragas – RAG Evaluation Fundamentals",
        "days": [
            {"topic": "Ragas Setup & Core Concepts",
             "tasks": ["Install ragas", "Study: evaluation metrics (faithfulness, relevancy)", "Run: basic evaluation on your RAG pipeline"],
             "resources": ["https://docs.ragas.io/en/stable/"]},
            {"topic": "Ragas – Evaluation Dataset Creation",
             "tasks": ["Create: ground truth Q&A dataset (20+ pairs)", "Learn: synthetic test data generation with Ragas", "Run: comprehensive evaluation", "Analyze: metric scores and identify weaknesses", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "Ragas – Advanced Metrics",
             "tasks": ["Study: context precision, context recall", "Study: answer similarity, answer correctness", "Run: full metric suite on your RAG", "Compare: metrics before/after optimization", "Document: evaluation methodology"],
             "resources": []},
            {"topic": "RAG Optimization Based on Evals",
             "tasks": ["Identify: lowest-scoring areas from Ragas", "Optimize: retrieval strategy for better context", "Re-run: evaluations to measure improvement"],
             "resources": []},
            {"topic": "Evaluation Pipeline Automation",
             "tasks": ["Build: automated eval pipeline (run on code change)", "Create: evaluation dashboard in Streamlit", "Add: evaluation history tracking"],
             "resources": []},
            {"topic": "Evaluation Best Practices",
             "tasks": ["Study: human vs automated evaluation", "Build: human evaluation interface", "Compare: human scores vs Ragas scores"],
             "resources": []},
            {"topic": "Week 20 Review",
             "tasks": ["Review Ragas evaluation concepts", "RAG pipeline has automated evals", "LeetCode: 1 medium problem"],
             "resources": []},
        ],
    },
    {   # Week 21: Observability & Monitoring
        "week": 21,
        "phase": "Phase 3: Security, Evals & Production",
        "theme": "AI Observability & Production Monitoring",
        "days": [
            {"topic": "LangSmith Deep Dive",
             "tasks": ["Set up LangSmith project", "Trace: all agent interactions", "Analyze: latency, token usage, error rates"],
             "resources": ["https://smith.langchain.com/"]},
            {"topic": "Custom Observability",
             "tasks": ["Build: custom metrics collection", "Implement: structured logging for agents", "Track: cost per query, success rate", "Build: alerting for failures", "LeetCode: 1 medium problem"],
             "resources": []},
            {"topic": "Production Error Handling",
             "tasks": ["Implement: graceful degradation patterns", "Build: fallback chains for agent failures", "Add: retry logic with exponential backoff", "Test: chaos scenarios (API down, timeout)", "Document: error handling strategy"],
             "resources": []},
            {"topic": "Performance Optimization",
             "tasks": ["Profile: agent response times", "Implement: caching strategies", "Optimize: prompt length and token usage"],
             "resources": []},
            {"topic": "CI/CD for AI Applications",
             "tasks": ["Set up GitHub Actions for your projects", "Add: automated testing pipeline", "Add: linting and type checking"],
             "resources": ["https://docs.github.com/en/actions"]},
            {"topic": "Production Readiness Checklist",
             "tasks": ["Create: production deployment checklist", "Review: all projects against checklist", "Document: infrastructure requirements"],
             "resources": []},
            {"topic": "Week 21 Review + Networking",
             "tasks": ["Review observability patterns", "All projects have monitoring", "LeetCode: 1 medium problem", "🤝 Networking: request informational interviews at target companies", "🤝 Write LinkedIn post about your AI security learnings"],
             "resources": []},
        ],
    },
    {   # Week 22: Eval Pipeline Complete + Interview Prep Start
        "week": 22,
        "phase": "Phase 3: Security, Evals & Production",
        "theme": "Evaluation Pipeline & Interview Prep Start",
        "days": [
            {"topic": "Complete Evaluation Pipeline",
             "tasks": ["Finalize: automated eval pipeline for all projects", "Generate: comprehensive evaluation report", "Create: evaluation dashboard"],
             "resources": []},
            {"topic": "System Design Practice (RADIO Framework)",
             "tasks": ["Study RADIO framework in depth", "Practice: design a RAG pipeline (whiteboard)", "Practice: design a SQL agent architecture", "Practice: design an evaluation system", "Mock interview: system design question"],
             "resources": []},
            {"topic": "Behavioral Interview Prep",
             "tasks": ["Prepare: STAR stories for each role/project", "Prepare: 'Why FDE?' narrative", "Prepare: 'Data privacy stakeholder' story (HIPAA/OCC)", "Practice: 'Tell me about yourself' (2 min pitch)", "Prepare: 'Why career transition?' answer"],
             "resources": []},
            {"topic": "Technical Interview Prep – Python",
             "tasks": ["Review: Python fundamentals for interviews", "Practice: live coding (no IDE, just whiteboard)", "Review: all 30+ LeetCode solutions"],
             "resources": []},
            {"topic": "Technical Interview Prep – AI/ML",
             "tasks": ["Review: RAG pipeline design", "Review: agent architecture patterns", "Practice: explain LangGraph to a non-technical person"],
             "resources": []},
            {"topic": "Resume Update Sprint",
             "tasks": ["Rewrite resume as 'Principal AI Data Infrastructure Architect'", "Highlight: regulatory compliance experience", "Add: all new projects and skills"],
             "resources": []},
            {"topic": "Week 22 Review & Phase 3B Complete",
             "tasks": ["Phase 3B checkpoint: evals complete", "Interview prep materials ready", "LeetCode: review 5 key problems"],
             "resources": []},
        ],
    },
    # ═══════════════════════════════════════════════════════════════════
    # PHASE 3C – Capstone Project (Weeks 23-24)
    # ═══════════════════════════════════════════════════════════════════
    {   # Week 23: Capstone – Design & Implementation
        "week": 23,
        "phase": "Phase 3: Security, Evals & Production",
        "theme": "Capstone: Regulatory-Aware SQL Agent (Build)",
        "days": [
            {"topic": "Capstone – Architecture Design",
             "tasks": ["Design full system using RADIO framework", "Define: components, data flow, security layers", "Create: detailed architecture diagram"],
             "resources": []},
            {"topic": "Capstone – Core SQL Agent Build",
             "tasks": ["Build: NL → SQL generation engine", "Integrate: LangGraph for workflow management", "Implement: schema discovery and injection", "Add: query validation layer", "Test: basic query generation"],
             "resources": []},
            {"topic": "Capstone – Error Correction Loop",
             "tasks": ["Build: autonomous error correction with LangGraph", "Implement: SQL error parser", "Build: retry with error context injection", "Test: correction loop on complex queries", "Benchmark: correction success rate"],
             "resources": []},
            {"topic": "Capstone – Security & PII Layer",
             "tasks": ["Integrate: Microsoft Presidio for PII redaction", "Add: input sanitization (prompt injection defense)", "Implement: output filtering for sensitive data"],
             "resources": []},
            {"topic": "Capstone – Evaluation Integration",
             "tasks": ["Add: Ragas evaluation pipeline", "Create: test dataset for SQL agent", "Run: automated accuracy evaluation"],
             "resources": []},
            {"topic": "Capstone – API & UI",
             "tasks": ["Build: FastAPI endpoints for the agent", "Build: Streamlit demo interface", "Add: query history and audit log"],
             "resources": []},
            {"topic": "Capstone – Integration Testing",
             "tasks": ["Run full end-to-end tests", "Fix bugs and edge cases", "Performance optimization pass"],
             "resources": []},
        ],
    },
    {   # Week 24: Capstone – Polish & Documentation
        "week": 24,
        "phase": "Phase 3: Security, Evals & Production",
        "theme": "Capstone: Polish, Document & Deploy",
        "days": [
            {"topic": "Capstone – Docker & Deployment",
             "tasks": ["Create: Dockerfile and docker-compose", "Deploy: to Railway/Render (free tier)", "Test: deployed version works correctly"],
             "resources": []},
            {"topic": "Capstone – Documentation Sprint",
             "tasks": ["Write: comprehensive README", "Write: RADIO framework system design doc", "Create: architecture diagrams", "Write: security documentation", "Record: demo walkthrough video"],
             "resources": []},
            {"topic": "Capstone – Final Testing & Polish",
             "tasks": ["Final round of testing", "UI/UX polish", "Code cleanup and commenting", "Ensure all tests pass", "Generate: final evaluation report"],
             "resources": []},
            {"topic": "Portfolio Final Review",
             "tasks": ["Review all GitHub projects", "Ensure consistent quality across repos", "Update GitHub profile README"],
             "resources": []},
            {"topic": "LinkedIn & Online Presence",
             "tasks": ["Write: detailed LinkedIn post about capstone", "Update LinkedIn with new skills/title", "Prepare: portfolio website or Notion page"],
             "resources": []},
            {"topic": "Mock Interview Day",
             "tasks": ["Full mock interview: technical + behavioral", "Practice: whiteboard system design", "Practice: live coding challenge"],
             "resources": []},
            {"topic": "Capstone & Phase 3 Complete 🎉",
             "tasks": ["Final capstone review", "Phase 3 checkpoint: all skills demonstrated", "Celebrate completing the capstone!"],
             "resources": []},
        ],
    },
    # ═══════════════════════════════════════════════════════════════════
    # BUFFER – Interview Prep & Job Search (Weeks 25-26)
    # ═══════════════════════════════════════════════════════════════════
    {   # Week 25: Application Sprint
        "week": 25,
        "phase": "Job Search & Interview Prep",
        "theme": "Application Sprint & Networking",
        "days": [
            {"topic": "Job Search Strategy",
             "tasks": ["Finalize target company list", "Research: Palantir, Databricks, Scale AI, Anthropic", "Identify: FDE/Solutions Engineer openings"],
             "resources": []},
            {"topic": "Application Day 1",
             "tasks": ["Tailor resume for 3 specific roles", "Write cover letters", "Submit applications", "Reach out to 2 people at target companies", "LeetCode: review 3 key problems"],
             "resources": []},
            {"topic": "Application Day 2 + Mock Interviews",
             "tasks": ["Submit 3 more applications", "Mock technical interview (1 hour)", "Mock behavioral interview (30 min)", "Review: system design patterns", "Network: message 3 FDEs on LinkedIn"],
             "resources": []},
            {"topic": "Technical Review Day",
             "tasks": ["Review: Python, LangChain, LangGraph", "Practice: live coding with timer", "Review: security and compliance concepts"],
             "resources": []},
            {"topic": "System Design Practice",
             "tasks": ["Practice: design a regulatory-aware AI system", "Practice: design a multi-tenant RAG platform", "Review: RADIO framework responses"],
             "resources": []},
            {"topic": "Application Day 3",
             "tasks": ["Submit 3 more applications", "Follow up on previous applications", "Network: attend virtual AI meetup"],
             "resources": []},
            {"topic": "Week 25 Review",
             "tasks": ["Track: applications submitted", "Review: interview feedback", "Adjust: strategy based on responses"],
             "resources": []},
        ],
    },
    {   # Week 26: Final Push
        "week": 26,
        "phase": "Job Search & Interview Prep",
        "theme": "Final Interview Prep & Continued Applications",
        "days": [
            {"topic": "Interview Prep Intensive",
             "tasks": ["Full mock interview (technical + behavioral)", "Practice: 'Parse 1GB JSON into SQL' live coding", "Review: RAG pipeline whiteboard design"],
             "resources": []},
            {"topic": "Application Day 4 + Networking",
             "tasks": ["Submit 3 more applications", "Follow up on Week 25 applications", "Network: reach out to hiring managers", "Polish: online presence (GitHub, LinkedIn)", "LeetCode: solve 2 medium problems under timer"],
             "resources": []},
            {"topic": "Deep Dive Review Day",
             "tasks": ["Review: weakest areas from mock interviews", "Practice: specific technical questions", "Review: all portfolio projects", "Prepare: questions to ask interviewers", "Update: study tracker with final reflections"],
             "resources": []},
            {"topic": "Application Day 5",
             "tasks": ["Submit applications to stretch companies", "Research: more companies that sponsor H1B", "Network: ask for referrals"],
             "resources": []},
            {"topic": "Continued Interview Prep",
             "tasks": ["Practice: system design (45 min timed)", "Practice: behavioral STAR stories", "Review: capstone project demo"],
             "resources": []},
            {"topic": "Strategy Review",
             "tasks": ["Review: all applications and responses", "Adjust: resume based on feedback", "Plan: next 30 days of job search"],
             "resources": []},
            {"topic": "🎓 Roadmap Complete! Next Steps",
             "tasks": ["Celebrate completing the 6-month roadmap!", "Continue: daily LeetCode practice", "Continue: applying and networking", "Keep building: new projects to stay sharp"],
             "resources": []},
        ],
    },
]


# ── Schedule Generation ──────────────────────────────────────────────

DAY_NAMES = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
             "Saturday", "Sunday"]

# Our week layout starting from Friday:
# index 0=Fri, 1=Sat, 2=Sun, 3=Mon, 4=Tue, 5=Wed, 6=Thu
WEEK_DAY_ORDER = [4, 5, 6, 0, 1, 2, 3]  # Fri=4, Sat=5, Sun=6, Mon=0 ...


def generate_schedule() -> List[Dict]:
    """Generate the full day-by-day schedule with actual dates."""
    schedule = []
    for week_plan in WEEKLY_PLANS:
        week_num = week_plan["week"]
        week_start = START_DATE + timedelta(weeks=week_num - 1)
        for i, day_plan in enumerate(week_plan["days"]):
            day_date = week_start + timedelta(days=i)
            weekday = day_date.weekday()  # 0=Mon ... 6=Sun
            is_weekend = weekday >= 5  # Sat=5, Sun=6
            hours = 7 if is_weekend else 3.25
            schedule.append({
                "date": day_date,
                "date_str": day_date.strftime("%Y-%m-%d"),
                "day_name": DAY_NAMES[weekday],
                "week": week_num,
                "phase": week_plan["phase"],
                "theme": week_plan["theme"],
                "topic": day_plan["topic"],
                "tasks": day_plan["tasks"],
                "resources": day_plan.get("resources", []),
                "target_hours": hours,
                "is_weekend": is_weekend,
            })
    return schedule


# Pre-generate for import
SCHEDULE = generate_schedule()
